Forbid configurations with invalid *_access line
Squid reports several non-fatal level-0 messages:

    ERROR: aclParseAccessLine: missing 'allow' or 'deny'.
    expecting 'allow' or 'deny', got 'foo'
    Access line contains no ACL's, skipping

These messages have been around since 7dd57fa2.

On one hand, ignoring such lines give admin some freedom to maintain
'almost' correct configurations, forgiving spelling errors. On the other
hand, such invalid configurations may present security risks,
outweighing these insignificant benefits.