Bug 5343: Fix GCC v14 not finding std::find()
    Reply.cc:198: error: no matching function for call to find(...)

The required STL header was missed in 2023 commit 27c3677.

----

Cherry-picked master/v7 commit 0002264bc7ed380be27bdb32ee2627cdb7db75c8,
resolved a trivial conflict, and added similar change to
src/proxyp/OutgoingConfig.cc that was not present in that commit.