Fix build with clang v15.0.6 [-Wdeprecated-non-prototype]
clang v15.0.6 distributed with Fedora Rawhide complains about function
definitions using K&R style:

    lib/snmplib/mib.c:229:1: error: a function definition without a
    prototype is deprecated in all versions of C and is not supported in
    C2x [-Werror,-Wdeprecated-non-prototype]

----

Cherry-picked v5 commit bc3cada6edbfb69639a1be0dafbf3dce21fec111.