Removed redundant extern "C"
We should not mark standalone static functions with `extern "C"` because
this is contradictory: on one hand, static stands for private to that
specific file and cannot be seen by the linker. On the other, extern "C"
modifies external linkage so that the linker can share the function
across different files.

Compiler does not allow marking such individual functions with extern
"C":

    error: cannot combine with previous 'extern' declaration specifier

Still, it allows to mark an entire {} block. In this case, the compiler
does not complain, but seem to ignore the `extern "C"` marking in favor
of 'static'.