Fix trickling of bodyless messages (e.g., GET requests)
    ERROR: Squid BUG: assurance failed: state.sending == State::sendingVirgin
    exception location: ModXact.cc(816) trickleMore

Do not schedule a body drop if there is no virgin body. Doing so is
wasteful and triggers state.sending assertion in trickleMore() because
we are not sending a virgin body.

Also honor body-drop-size=0.