Bug 5332: TCP_SWAPFAIL_MISS with UFS collapsed_forwarding
When collapsed_forwarding is enabled, collapsed revalidation requests
created UFS cache_dir entries with `ksRevalidation` key scope, which is
banned from caches. If Squid then decided to forward the being-cached
revalidation response to the client, `ksRevalidation` scope was cleared
in Store index, making the entry discoverable by regular transactions
(using `ksDefault` scope), even though on-disk entry bytes had a
`ksRevalidation` key. Attempts to load discovered entries from the cache
resulted in level-1 errors:

    ERROR: Failed to unpack Store entry metadata: swap meta MD5 mismatch
    exception location: SwapMetaIn.cc(89) CheckSwapMetaKey

2016 commit 1a210de4 placed `clearPublicKeyScope()` call inside
`clientReplyContext`, probably because it felt natural to clear
`ksRevalidation` scope in the same class that added it. That incorrect
placement resulted in entries with `ksRevalidation` keys getting cached.
Squid now clears `ksRevalidation` scope much earlier, in `makePublic()`,
before anything is written to Store, protecting caches from storing
`ksRevalidation` keys and narrowing revalidation-need window for
incoming requests.

This fix does not affect Squid caching decisions. For example,
`HttpStateData::reusableReply()` method has not changed and
`HttpStateData::haveParsedReplyHeaders()` still calls `makePublic()` for
responses that should be cached and `makePrivate()` for others.

This fix does not affect how Squid decides whether to give HTTP client
the old response, the current revalidation response, or restart from
scratch: `clientReplyContext::handleIMSReply()` conditions for calling
`sendClientOldEntry()`, `sendClientUpstreamResponse()`, or
`processMiss()` remain the same. Fixed code may `sendClientOldEntry()`
that got marked for release by adjusted `makePublic()`, but that marking
is not expected to affect what is being sent. Similarly, fixed code may
`sendClientUpstreamResponse()` using a public Store entry with
`ksDefault` scope instead of `ksRevalidate`, but that scope is not
expected to affect what is being sent.

Before this fix, some old entries were not purged because
`HttpStateData` called `makePublic()` (with the intent to cache the new
revalidation response and, hence, purge the old one), but `makePublic()`
did nothing for the already public `ksRevalidation` entries, and
`handleIMSReply()` went on `sendClientOldEntry()` path that did not call
`clearPublicKeyScope()`. Fixed code fulfills that `HttpStateData` intent
by storing cachable revalidation responses with `ksDefault` scope, which
is a positive change[^1].  We are not aware of such problems, but if
that intent is wrong in some cases, then those bugs should be fixed.
However, such bugs (if any) would also affect non-collapsed (i.e.
`ksDefault`) responses, and fixing all of that is out of scope here.

Also fixed `StoreEntry::mayStartSwapOut()` to not swapout private
entries.  The problem exists since 4310f8b. Storing private entries
violated Store metadata invariant: on startup, rock store produced
"Invalid entries" report.  UFS also stored private entries, but the
effect was hidden (except for disk IO overhead) because the just stored
disk entry was almost immediately removed by
`UFSSwapDir::evictCached()`.

[^1]: This change actually _restores_ the corresponding Squid behavior
prior to 2016 commit 1a210de4. We believe that old entry preservation
introduced by that commit in those cases was _accidental_. It may have
also been harmful because preserved old entry may keep triggering
(expensive) revalidation.

----

Apply SQUID-1032-tcp-swapfail-miss-with-ufs-collapsed-forwarding-v7
changes up to 4b6ecd76 in hope to provide a more "long-term stable"
foundation for the upcoming cache-refresh-response test fix.