Bug 5069: Keep listening after getsockname() error
    ERROR: Stopped accepting connections:
    error: getsockname() failed to locate local-IP on ...

In many cases, these failures are intermittent client-triggered errors
(e.g., client shut down the accepted socket); Squid will successfully
accept other connections and, hence, should keep listening for them.

----

Cherry-picked master/v7 commit 3471f3722196ac29834f7c6bcf277f1cef06baa8.