Enforce cbdata-awareness for ipcache_nbgethostbyname/eventAdd
... arguments: All ipcache_nbgethostbyname() callers that supply
callback data, must supply a cbdata-aware callback data. This
requirement is now checked at compile time. The same statements apply to
all remaining eventAdd() callers, but some earlier callers were changed
to call eventAddBare() instead, as detailed further below.

These improvements are especially valuable for detecting refactoring
bugs related to replacement of cbdata with proper reference counting.

Inside evenAdd(), we cannot statically assert that the boolean `cbdata`
parameter value is false, so we split callers into three categories:

* eventAdd() callers that use a cbdata-protected argument.
* eventAdd() callers that use an std::nullptr argument.
* eventAddBare() callers that use non-cbdata-protected argument.

This split is safe because code would not compile if we missed a caller.

This enhancement exposed several problematic eventAdd() callers:

* Fixed several eventAdd() calls with AsyncJob parameters that disabled
  cbdata protection. Most likely, these bugs did not affect these jobs
  because these jobs do not normally end until the corresponding event
  fires. However, an exception, for example, may kill a job before it
  reaches a doneAll() state, so we should not rely on the job object
  lifetime exceeding event lifetime.

* Annotated complex IpcIoFile::open() use case were the caller disabled
  cbdata protection for a cbdata-capable type. We have not enabled
  cbdata protections here because it would require adjusting other
  IpcIoFile code that is currently written to assume raw/unsafe
  pointers. This caller uses eventAddBare() now, of course.

The long-term goal of migrating event.h API to AsyncCalls remains valid.
This change allows us to gain cbdata assurances sooner and may help with
that migration as well. These positives outweigh the extra diff noise.

Also polished TunnelStateData::copyRead() eventAdd() caller: Most
callers use 0 or 1 for event weights. Follow that pattern instead of
using a misleading "true" for weights (that is commonly used to enable
cbdata protections).

Also simplified callers while facilitating future migration away from
event weights. Most likely, the concept of a "heavy" event is not useful
in modern Squid code. EventScheduler::checkEvents() has a related TODO
(that this change may help address with less noise). This change does
not make any heavy events lighter though. To reduce diff noise, we only
removed explicit (light) weights from eventAdd() calls that had the
corresponding code line modified for other in-scope reasons.

Also fixed stubs used by testSBuf. Do not duplicate (poorly) eventAdd()
and MemObject::endOffset() stubs. These stubs were duplicated since
inception in 2013 commit 412da427.

Sample error messages after injecting buggy code

* ... into icpIncomingConnectionOpened():

    ipcache_nbgethostbyname(nullptr, mcastJoinGroups, &answer);

    ipcache.h: In instantiation of ipcache_nbgethostbyname(...)
        [with HandlerData = Ipc::StartListeningAnswer* ...]:
    icp_v2.cc:743:32: required from here
    ipcache.h:241:47: error: static assertion failed
        static_assert(CbdataProtected<HandlerData>());

* ... into Rock::Rebuild::checkpoint():

    eventAdd("Rock::Rebuild", Rock::Rebuild::Steps, parts, 0.01, 1);

    event.h: In instantiation of eventAdd(...)
        [with HandlerData = Rock::LoadingParts* ...]:
    rock/RockRebuild.cc:379:17: required from here
    event.h:41:47: error: static assertion failed
        static_assert(CbdataProtected<HandlerData>());

----

Squash-merged branch SQUID-1074-guarantee-cbdata-arg-in-eventAdd-bag0 as
of commit 720d7594 which also contained (i.e. was based on top of)
SQUID-1074-guarantee-cbdata-arg-in-ipcache-nbgethostbyname as of commit
772ead4b.