paranoid_hit_validation mistreats appending hits
    ERROR: Squid BUG: purging corrupted cache entry...
    lock=...RWA

One worker cannot validate the total cache entry size when another
worker is appending to that entry because the size of an individual
entry slice and the total entry size cannot be updated as one size,
atomically. Since inception in 2020 commit b2aca62,
paranoid_hit_validation implementation missed that caveat and
occasionally logged false "corrupted cache entry" reports.

Also delayed unlockHeaders() call for invalid (and, hence, doomed) hits
to reduce reporting of stale entry information (compared to the entry
state that the validation code has examined). Some entry metadata may be
updated by other workers after we call unlockHeaders(). Some metadata
cannot be protected that way, but we should protect what we can.

----

Cherry-picked SQUID-960-no-validation-of-appending-entries-bag51
commit 9d16c6c42b860f20a59b649ffecf2386d993c4a8.