fixup: Fix build --with-gnutls [-Werror=unused-but-set-variable]
    src/security/PeerOptions.cc:716:20: error: variable 'errorMessage'
        set but not used

Broken since the first branch commit.