Set SSL_OP_LEGACY_SERVER_CONNECT when peeking at servers
Our TLS Server Hello parser does not treat legacy servers specially, but
enabling legacy server support in OpenSSL allows OpenSSL to advance
enough in its Server Hello processing to provide our SslBump code with
the server certificate (that we then validate). Successful certificate
validation, in turn, may result in Squid splicing the connection, even
if OpenSSL detected other errors:

    noteNegotiationError: hold TLS write on FD 15 despite
    SQUID_TLS_ERR_CONNECT+TLS_LIB_ERR=2000068+TLS_IO_ERR=1

TODO: When staring, apply tls_outgoing_options.

----

Cherry-picked bag52a commit 9ef428cc14073683048c1e4af8dafd8f03f4d35e.