fixup: Avoid runtime checks; do not add cbdata validity checks
Sample error message after injecting the following buggy code into
icpIncomingConnectionOpened():

    ipcache_nbgethostbyname(nullptr, mcastJoinGroups, &answer);

    icp_v2.cc:745:28:   required from here
    ipcache.h:244:62: error: ‘toCbdata’ is not a member of
        ‘HandleDataClass’ {aka ‘Ipc::StartListeningAnswer’}