fixup: Fix layer-01-minimal build by restoring a required include
    Server.cc:162:82: error: incomplete type LogTagsErrors

Probably broken in recent commit 6aa60f43.