Purge disk cache entries with unparsable metadata or HTTP headers
If we fail to parse cache entry metadata or HTTP headers once, we will
probably fail again and again until the entry is removed or replaced.
Reduce the number of such failures by marking the entry for deletion.

    ERROR: Failed to unpack Store entry metadata:
           store entry metadata prefix is corrupted

    ERROR: Cannot parse on-disk HTTP headers

The first ERROR was observed with earlier Squid code, especially after
Squid restarts. It is not clear what causes it, but it feels like a bug.
It might be fixed by now.

In error-injection tests, the client request that hits the problematic
cache_dir entry is logged as TCP_SWAPFAIL_MISS/200: The client request
is successfully satisfied by the origin server after the reported swapin
failure. The fresh origin server response should be cached, replacing
the problematic cache_dir entry. Until Squid starts caching that origin
server response (or, at the very least, creates a public entry to store
the future response, as may happen in collapsed forwarding cases), other
requests may continue to hit the same problematic cache_dir entry,
logging more ERRORs. This change closes that window.

The second ERROR deserves similar treatment.

----

Squash-merged SQUID-1141-mark-corrupted-metadata-cache-entry-bag0 as of
commit 89dc35b0.