CI: Functionality tests should wait for squid-overlord start
  Error: connect ECONNREFUSED 127.0.0.1:13128
      at .../daft/src/overlord/Proxy.js:745:23

Recently, the first CI functionality test started to occasionally fail
because squid-overlord, the script responsible for starting Squid is not
yet listening for commands when the first CI test starts. This happens
when our "sudo --background ..." command backgrounds quickly, but the
script it launches starts slowly.

Requires squid-overlord commit e4e1a31e that daemonizes squid-overlord
program after it starts listening for commands, removing "is it ready?"
guesswork from the script caller.