Preprocess squid.conf _before_ applying any directives
Split monolithic (re)configuration sequence into two distinct stages:

1. preprocessing of default settings and admin-specified config file(s);
2. parsing of preprocessed directives to update Config.* and friends.

This segregation allows Squid to examine new configuration (at directive
name and opaque contents level) before that configuration (is parsed
and) takes effect. This "look before you leap" check already makes
reconfiguration safer (see below). Followup changes will allow Squid to
reduce unwanted reconfiguration side effects in many common use cases.

Besides minor cache.log message modifications, there is one known
admin-visible effect of these changes:

* Reconfiguration attempts with unsupported directive names, malformed
  preprocessor conditionals, or misspelled preprocessor include files
  are now refused, preserving existing runtime state (configuration,
  listening sockets, in-progress transactions, etc.):

    Processing Configuration File: .../squid.conf (depth 0)
    ERROR: Unrecognized configuration directive name: http_accesses
        directive location: .../squid.conf(6)
    Refusing to reconfigure after a preprocessing failure;
        error: Found 1 invalid configuration line(s)

----

Cherry-picked bag61 commit d6a568874530ccee94600a81906fbcdd44c1f561 and
its two fixups (bag61 1f3a355a and bag61 commit 960e9fab). Removed
out-of-scope parts that deserve dedicated PRs. Resolved many conflicts,
including complex ones. Fixed "make check". Polished. The corresponding
extra changes were done for several reasons:

* To extract preprocessor-focused improvements summarized earlier above
  from bag61 commit that also contained initial smooth_reconfiguration
  support for "acl" directives.

* To re-sync with recent parsing-related changes (e.g., earlier branch
  commit 875a45e5 and master/v7 commits ed8b0404 and ef3617fb). Bag61
  also lacked configuration parsing tests (master/v6 commit 6c9a5e8d).

* To compensate for the lack of SquidConfig::lifecycleStart() that is
  waiting for up-porting of our "Do not collapse ssl_crtd requests
  across reconfigurations" fix (i.e.
  SQUID-672-no-collapsing-across-ssl-crtd-reconfig commit a7f0c0dc).

* To address a few XXXs and TODOs in hope that we will be able to use
  this commit for the official review, without the need to address those
  defects in a separate/PR branch and then backport those changes to
  this branch (that is likely to advance much further by then). In
  hindsight, I should have used dedicated commits for such changes
  because there are too many of them to manage in a single commit and
  because squashing them like that would make it even more difficult to
  identify those "out-of-scope parts that deserve dedicated PRs" later.
  I created SQUID-1039-pp-before-applying-bag71 after realizing that.