Make configuration_includes_quoted_values a preprocessor instruction
configuration_includes_quoted_values directive adjusted a couple of
global variables that directive parsing code used when parsing
subsequent directives. During smooth reconfiguration, unchanged
configuration_includes_quoted_values directives are completely ignored,
so those globals were left at their last/stale setting, effectively
subjecting all pliable directives to that last/stale context, even when
some pliable directives were declared and, hence, should have been
processed in a different configuration_includes_quoted_values context.

This change converts configuration_includes_quoted_values from a
configuration directive into a preprocessor instruction and assigns
correct configuration_includes_quoted_values context to each
preprocessed directive. The same globals are reset (according to the
directive-assigned context) before parsing each directive.

As a preprocessor instruction, configuration_includes_quoted_values
effectively becomes "pliable" from smooth reconfiguration point of view,
although that term is best reserved for configuration _directives_.

Also fixed support for directive parameter files included by some
test-suite/squidconf tests. Those files were never found. 2022 commit
d37a3744 probably missed this bug because the corresponding (see below)
`squid -k parse` failures do not result in non-zero exit status code.
The latter problem deserves a dedicated fix.

    ERROR: Can not open file empty.conf for reading
        configuration context: .../regressions-3.4.0.1.conf(27) acl

Also polished Configuration::Diff::noteAppearance() name.

----

Squash-merged (fast-forward eligible)
SQUID-1064-make-configuration-includes-quoted-values-a-preprocessor-instruction-bag0
as of commit 04abbe9a.