fixup: Do not pool connections to disappeared cache_peers
    ERROR: Squid BUG: assurance failed: !result->toGoneCachePeer()
        exception location: pconn.cc(280) findUseable

Branch commit 89f5073d closed idle pooled connections toGoneCachePeer().
Branch commit 38269962 fixed that implementation to assert that pools
have no toGoneCachePeer() connections, but that fixup was insufficient:
We also need to ensure that toGoneCachePeer() connections are not pushed
into the pull by transactions that finish using those connections
_after_ CachePeers::remove() call closeAllTo() to clean the pools from
the already idle connections toGoneCachePeer().

Also do not attempt to pool idle HTTP connections toGoneCachePeer().
This is not necessary after the PconnPool::push() change, but the old
COMPLETE_PERSISTENT_MSG classification essentially lied about
persistence, and we do a lot of extra work when the connection is
classified as persistent/reusable. Fixing classification avoids that
extra work.

Also polished Ftp::Relay::serverComplete() that is similar to http.cc
code being improved in this commit.

Also added debugging that was useful in this bug triage.