fixup: Fix --without-openssl and --with-gnutls builds
Broken since recent branch commit 591e106a.

Builds --without-openssl
------------------------

    KeyLog.cc: error: 'OpenSSL_version' was not declared in this scope

KeyLog.cc is compiled regardless of USE_OPENSSL, so it cannot use
OpenSSL APIs without checking USE_OPENSSL.

Builds --with-gnutls
--------------------

Security::KeyLog must not be created --without-openssl.

    Session.cc:63:40: error: invalid initialization of reference of type
    `const Security::Connection&` from expression of type
    `gnutls_session_int`
    Security::KeyLoggingCheckpoint(*session);

More work is needed to get GnuTLS build to work with KeyLog, of course,
but this change fixes caller compilation in --with-gnutls builds. The
mismatch between "connection" and "session" makes it difficult to place
this workaround inside KeyLoggingCheckpoint() itself. This terminology
clash between OpenSSL and GnuTLS code predates KeyLogger.