Fix libntlmauth build on current Fedora Rawhide
    ntlmauth.cc:187: error: 'time' was not declared in this scope

----

Cherry-picked master/v6 commit 9b7c14a53ee35e0960aab20ab75e8a2f01719b82.