Fix GCC v13 build [-Warray-bounds]
    src/ipc/mem/FlexibleArray.h:34:52: error: array subscript -1 is
    below array bounds of 'int [1]' [-Werror=array-bounds]

...

----

Cherry-picked master/v7 commit 6f6db8c5b76b4e49059cd348d0e7afb3616f0e6b
and resolved a low-complexity conflict to sync backporting of this fix
with master/v7. We backported a v5 version in bag51 commit 225f133.