Fix build with clang v15.0.6 [-Wunused-but-set-variable]
clang v15.0.6 distributed with Fedora Rawhide complains about a variable
that is updated but never used:

    net_db.cc:230:9: error: variable 'removed' set but not used
    [-Werror,-Wunused-but-set-variable]`

----

Cherry-picked v5 commit 0dff06676e8acec5f864a547cf25292226ade534.