Fix time_t type conflicts in libdebug
    error: cannot convert 'const long int*' to 'const time_t*'

On Windows, time_t is 64-bit, and long is not.

----

Cherry-picked master/v7 1520f3adddfcd347932bc074a1f81e13a0d96249.