Remove bundled GnuRegex library
Modern operating systems provide a functioning regex
library, so we don't need to carry one anymore.

----

Cherry-picked master/v6 commit 2e0942f94f80eb33c51e3dfa5d1fde35783fd8c8
because --enable-gnuregex in layer-02-maximus builds breaks regex tests
enabled in branch commit b432a5d:

    ERROR: Squid successfully parsed malformed
    ./squidconf/bad-regex.conf instead of rejecting it

Resolved easy conflicts due to an out-of-order backport in branch commit
41ce73b (Delete trailing whitespace) and the lack of backport of
master/v6 commit 5a2409b (Remove --disable-loadable-modules).