fixup: Fix non-OpenSSL builds after branch commit f401a51
    src/tests/stub_libsecurity.cc:157:8: error:
    time_t Security::ToPosixTime(const Time&)
    defined but not used [-Werror=unused-function]

And other, similar errors, evidently related to branch commit f401a51
`using Time = class {}` hack. TODO: Ideally, it would be better to keep
all three declarations as `using` aliases, but it is not clear whether
the advantages of doing so outweigh required extra code.

----

This or another test-builds.sh fix will need to be upported along with
other SQUID-718-setValidityRange-bag52a-based changes.