CI: Improve reliability of tests ran under Valgrind control
    Proxy execution environment can detect memory leaks
    Resetting proxy
    Error: proxy-reported problem(s):
        2026/05/28 04:14:10 kid3| FATAL: kid3 registration timed out

After we started running functionality tests under Valgrind control, we
began to see kid registration timeouts in GitHub Actions environment. We
speculate that those failures are due to Valgrind typically slowing down
Squid by a factor of 10 (at least) while GitHub Actions virtualization
environment adds performance instabilities.

This timeout increase would not be appropriate for most production
deployments because the vast majority of timed out registrations in
production are due to environment/configuration problems, and we want to
detect those problems and fail Squid startup ASAP. The old 6 second
timeout achieves a good risk/reward balance in those use cases, even
after we started to "delay listening ... until all kids are ready" (i.e.
after branch commit d6cbf00b).