Detail "Connection to cache_peer failed" ERRORs
    ERROR: Connection to such-and-such failed
    current master transaction: master1601

When Squid fails to connect to a cache_peer, the above level-1 ERROR
message is not sufficient to understand what went wrong because
access.log records for master1601 transaction are not going to detail
what HTTP connection establishment stage (e.g., TCP or TLS) has failed,
what TCP source address of the failed connection was, etc. This lack of
essential for triage details is especially evident in cases where these
failures are then successfully bypassed/handled by using another
cache_peer or a direct Squid-to-origin connection; access.log records do
not (and should not) have a history of retries.

Since there is no "outgoing-connections.log" that errors could refer to,
we have to detail these errors in cache.log. We can focus on cache_peer
(rather than origin) errors because, in most environments, they are
unexpected, may represent a misconfiguration, may result in the whole
cache_peer marked as DEAD, _and_ can be addressed by Squid admins.

This change addresses a corresponding CachePeer::countFailure() TODO.

We no longer count and report (at level-1) several rare failures that
are not deemed to be cache_peer faults (XXX: Give examples). TODO:
Check whether any new failure counting contexts were added.

----

Ported bag51 commit b58d875bd8ccb961759ba84f239fdefaa0ba6b3e, addressing
many complex merge conflicts: This branch already has "Do not blame
cache_peer for CONNECT error responses" changes (i.e. bag51 commits
7e5a8713 and bcd61029; v7 commit 2e7dea3c)... The footnote for the
ported commit said that it "Needs some polishing work, possibly a
different debugs() wrapping/handling, and adding missing
CountOutgoingConnectionSuccess() calls in tunnel.cc".

Also cherry-picked a small fixup: bag51 commit aa20154f.

This commit should bring this branch fully in sync with
SQUID-961-detail-cache-peer-conn-failures-bag51 as of commit f2fe3005.
Only these changes need to be polished and made official.