Recover from TCP DNS server connection establishment errors
    ERROR: Failed to connect to nameserver 127.0.0.1 using TCP.

After failing to establish a TCP connection to a DNS server, all DNS
queries that needed a TCP connection to that DNS server would timeout
because the nsvc object representing TCP connectivity got stuck in a
"queuing new queries but too busy to send any right now" state. Such
timeouts typically lead to HTTP 503 ERR_DNS_FAIL responses. This bug was
introduced when Comm closure handler registration was moved/delayed in
2010 commit cfd6652.

With this change, the affected nsvc object is destroyed, and Squid
attempts to open another TCP connection to the DNS server (when needed).
The original query is typically retried (subject to dns_timeout and
dns_retransmit_interval idiosyncrasies).

XXX: This fix increases the surface of reconfiguration and shutdown
problems documented in nsvc class destructor XXX.

----

Cherry-picked SQUID-998-stuck-dns-after-tc-to-down-server commit 0f5b296
(a.k.a. official PR 1861 that is currently titled
"Recover after failing to open a TCP connection to DNS server") and
resolved a trivial debugs() conflict. Also incorporated PR description
improvements into this commit message.