Preprocess squid.conf _before_ applying any directives
Split monolithic (re)configuration sequence into two distinct stages:

1. preprocessing of default settings and admin-specified config file(s);
2. parsing of preprocessed directives to update Config.* and friends.

This segregation allows Squid to examine new configuration (at directive
name and opaque contents level) before that configuration (is parsed
and) takes effect. This "look before you leap" check already makes
reconfiguration safer (see below). Followup changes will allow Squid to
reduce unwanted reconfiguration side effects in many common use cases.

Besides minor cache.log message modifications, there are two known
admin-visible effects of these changes:

* Reconfiguration attempts with unsupported directive names, malformed
  preprocessor conditionals, or misspelled preprocessor include files
  are now refused, preserving existing runtime state (configuration,
  listening sockets, in-progress transactions, etc.):

    Processing Configuration File: squid.conf (depth 0)
    ERROR: Unrecognized configuration directive name: http_accesses
        directive location: squid.conf(6)
    Refusing to reconfigure after a preprocessing failure;
        error: Found 1 invalid configuration line(s)

* Squid now rejects configurations with directives that have certain
  malformed ACL rules instead of skipping problematic directives. This
  somewhat out-of-scope change was done to prevent DEFAULT_IF_NONE
  complications after in-scope changes (in rare corner cases where old
  aclParseAccessLine() skipped bad directives as illustrated below).

```diff
- aclParseAccessLine: squid.conf line 13: http_access deny
- aclParseAccessLine: Access line contains no ACL's, skipping

+ FATAL: configuration failure: missing ACL name after 'deny'
+     exception location: Gadgets.cc(151) aclParseAccessLine
+     configuration location: squid.conf(13) http_access
+     configuration line: http_access deny
+     advice: Run 'squid -k parse' and check for ERRORs.
```

----

Fast-forwarded and squash-merged SQUID-1039-pp-before-applying-bag71 as
of commit cd72f22a.

See SQUID-1039-pp-before-applying-bag71 commit cd72f22a message for more
details regarding rejecting configurations with malformed ACLs.

See SQUID-1039-pp-before-applying-bag71 commit 3eca3708 message for more
details about this code origin.