CI: Upgrade Node and CodeQL versions
This update addressing numerous GitHub Actions warnings like these:

    Node.js 20 is deprecated. The following actions target Node.js 20
    but are being forced to run on Node.js 24: actions/checkout@v4,
    actions/upload-artifact@v4, hendrikmuhs/ccache-action@v1.2.19.
    https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/

    CodeQL Action v3 will be deprecated in December 2026. Please update
    all occurrences of the CodeQL Action in your workflow files to v4.
    https://github.blog/changelog/2025-10-28-upcoming-deprecation-of-codeql-action-v3/

While updating GitHub actions was easy, switching to Node v24 required
serious Daft work because of backward-incompatible changes in nodejs
module support. This update requires Daft commit d0386ef3 and
squid-dafts commit 7ebd9a8a that migrate Daft ecosystem to Node v24,
including addressing the following Daft errors:

    /home/runner/work/_temp/clones/daft/node_modules/esm/esm.js:1
    const __global__ = this;(function (require, module, __shared__)...
    TypeError: Function.prototype.apply was called on undefined,
        which is a undefined and not a function
        at Object.<anonymous> (.../clones/daft/src/cli/daft.js:7:18)
        ...
        at Module._load (node:internal/modules/cjs/loader:1379:12)
    Node.js v24.17.0

----

This work was stacked on top of SQUID-1142-shutdown-purges-deleted-bag0.
This upgrade, among other recent CI improvements, helps address sporadic
CI test failures, but more work is needed to solve that problem.