fixup: Fix build --with-gnutls [-Werror=unused-but-set-variable]
    src/security/PeerOptions.cc:716:20: error: variable 'errorMessage'
        set but not used

Broken since recent branch commit fbd703ba.

----

Cherry-picked (fast-forward eligible)
SQUID-1172-make-ca-load-failure-fatal-bag0 commit
ddf250a528c4ccea849a6d20f366088501ede152.