Fix OpenSSL build with GCC v15.1.1 [-Wformat-truncation=]
On arm64 Fedora 42:

    src/ssl/crtd_message.cc:132:39: error: '%zd' directive output may be
        truncated writing between 1 and 19 bytes into a region
        of size 10 [-Werror=format-truncation=]
        snprintf(buffer, sizeof(buffer), "%zd", body.length());

----

Cherry-picked master/v8 commit 41b2adf454a46f7b8e7925beb8ae368136dd80f0
to fix GitHub Actions `linux-distros(fedora-rawhide,gcc,maximus)`
slow.yaml test on this branch.