Do not activate heavy Ipc::Strand::receive() dependencies
    $ make check
    Strand.cc: undefined reference to IpcIoFile::HandleOpenResponse()
    Strand.cc: undefined reference to IpcIoFile::HandleNotification()
    Strand.cc: undefined reference to CollapsedForwarding::HandleNotification()

I was hoping to avoid this move in this branch, but it is the best
solution for fixing "make check". Many tests, including such complex
ones as testRock, test_http_range (refactored with XXX in the previous
branch commit in hope to avoid this move), and testHttpRequest link
libipc.la. That library contains Ipc::Strand::receive(). Unfortunately,
that method hard-codes knowledge about such heavy dependencies as cache
manager, SNMP, and IpcIoFile. Those dependencies did exist prior to this
branch changes, but the linker evidently ignore them because no code
reachable from the test case code called code located inside Strand.cc.
In other words, the linker did not need Strand.cc to satisfy any test
case dependencies.

This branch placed new stand-alone functions inside the Strand class:

    static void Init();
    static void InitTagged(const SBuf &);
    static void BarrierWait(const AsyncCallPointer &);

Any test program that includes those function callers "activates" all
Strand.cc code, dragging in those heavy Ipc::Strand::receive()
dependencies. To fix that, I explored several options, including these:

1. Move the Strand class to StrandJob.cc, partially addressing a known
   TODO. Git might recognize that the code was moved rather than
   completely rewritten, but the preservation of Strand.cc file name may
   hinder that. I also started to realize that Strand code does not
   really belong to libipc: Libipc should be a "generic IPC tools"
   library that does not contain any code specific to some kid kinds.

2a. Move the new functions into new src/Strand.cc file while keeping old
   ipc/Strand.cc intact. This minimizes ipc/Strand.cc changes but
   creates a second Strand.cc file (until we move the Strand class to
   src/StrandJob.cc or src/Strand.cc).

2b. Move the new functions into new src/StrandKid.cc file while keeping
   old ipc/Strand.cc intact. This minimizes ipc/Strand.cc changes but
   uses a somewhat odd file name (to avoid creating a second Strand.cc).

2c. Move the new functions into src/Instance.cc while keeping Strand.cc
   intact. This option also minimizes Strand.cc changes but creates a
   TODO: Move the new functions to src/Strand.cc (or similar) while
   moving the Strand class to src/StrandJob.cc. This option may
   complicate future Makefile.am conflict resolution because master/v8
   already has stub_Instance.cc while bag51 lacks it.

3. Refactor Ipc::Strand::receive() so that those heavy dependencies
   register callbacks (one per IPC message type) with Strand instead of
   relying on Strand methods hard-coding calls to cache manager and SNMP
   modules. In other words, use Ipc::Strand::configureMessageHandler()
   added in this commit to handle old "external" message types. This
   would require quite a few completely out-of-scope changes though.

This change is the first step in option 2b direction. That choice feels
like the lesser evil to me. This commit does not fix "make check".