fixup: Do not assert if Rock::HeaderUpdater entry goes private
    ERROR: Squid BUG: assurance failed: publicKey()

We may decide to use Rock::HeaderUpdater while the entry was still
public. The job should stop if the entry became private (e.g., it was
evicted before the job reached startWriting()) because we cannot write a
private entry to disk since recent branch commit 54ec0fe9 that added
the triggered assertion to StoreEntry::getSerialisedMetaData().

In observed logs, these assertions happened when
HttpStateData::haveParsedReplyHeaders() started caching a fresh entry,
and released the old/stale entry, resulting in a
StoreEntry::setPrivateKey() call for the latter. This code path may have
been added in an even more recent branch commit 7e8a9258.