CI: Work around Squid inability to find one OpenSSL version
... when two versions are installed and a custom OpenSSL version is
found by ./configure via pkgconfig

    /usr/include/openssl/macros.h:155:4: error: ...

The above errors are from the default OpenSSL headers that should not
be used but are used along with some of the customer OpenSSL version
headers, leading to conflicts.